blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from slugger import AutoSlugField
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):

    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from='title')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=self.slug)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag


def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/list_post.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/detail_view.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title}  comments: {cd['comments']}"
            send_mail(subject, message, 'joshuachinwendu@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/share.html', {'post': post, 'form': form, 'sent': sent})

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="{% static 'main.css' %}" rel="stylesheet" type="text/css">

    <title>Hello, world!</title>
  </head>
  <body>
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

blog/templates/blog/detail_view.html
{% extends 'base.html' %}

{% block content %}
    <ul>
        <li>Title: <a href="{% url 'blog:post_list' %}">{{ post.title }}</a></li>
        <li>authored by: {{ post.author }}</li>
        <li>Created on: {{ post.created }}</li>
        <li>slug: {{ post.slug }}</li>
        <li>Body: {{ post.body }}</li>
        <br>
        <li>Lorem text: {% lorem %}</li>
        <br>
        <li>You are viewing this on: {% now "jS F Y H:i" %}</li>
    </ul>
    <p>
        <a href="{% url 'blog:post_share' post.id %}">share this post</a>
    </p>


    {% if comments %}
        {% for comment in comments %}
            <p><strong>comment {{ forloop.counter }}</strong> {{ comment.name }} said {{ comment.body }}</p>
        {% endfor %}
        <p>{{ comments.count }} comment{{ comments.count|pluralize }}</p>
    {% else %}
        <p>{{ comments.count }} comment{{ comments.count|pluralize }}</p>
    {% endif %}
    <form method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

blog/templates/blog/list_post.html
{% extends 'base.html' %}

{% block content %}
    <h1>All Posts</h1>
    {% for post in posts %}
        <p>Tags: {{ post.tags.all|join:", " }}</p>
        <ul>
            <li>Title: <a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></li>
            <li>title: {{ post.title }}</li>
            <li>Author: {{ post.author }}</li>
            <li>created: {{ post.created }}</li>
            <li>slug: {{ post.slug }}</li>


        </ul>
    {% endfor %}
    {% include "blog/pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/pagination.html
<div>
    {% if page.has_previous %}
     <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span>
        page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
     <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
</div>

blog/templates/blog/share.html
{% extends 'base.html' %}

{% block content %}
    {% if sent %}
        <p>
            {{ post.title }} was sent successfully to {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>Share {{ post.title }} by email</h1>
        <form action="" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="send e-mail">
        </form>
    {% endif %}
{% endblock content %}